# Generated by Django 6.1.1 on 2026-09-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enigma',
            old_name='resposta',
            new_name='senha',
        ),
    ]
