# Generated by Django 6.1.1 on 2026-09-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_resposta_enigma_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enigma',
        ),
    ]
